# Generated by Django 5.1.1 on 2024-10-14 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("espacios", "0004_alter_espaciopublico_delegacion"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="instalaciondeportiva",
            name="delegacion",
        ),
        migrations.RemoveField(
            model_name="instalaciondeportiva",
            name="nombre",
        ),
      #  migrations.RemoveField(
      #       model_name="instalaciondeportiva",
      #      name="tipo",
      #  ),
        migrations.AddField(
            model_name="instalaciondeportiva",
            name="alcaldia",
            field=models.CharField(default="Sin alcaldía", max_length=100),
        ),
        migrations.AddField(
            model_name="instalaciondeportiva",
            name="costo",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="instalaciondeportiva",
            name="horario",
            field=models.CharField(default="Horario no disponible", max_length=100),
        ),
        migrations.AddField(
            model_name="instalaciondeportiva",
            name="nombre_instalacion",
            field=models.CharField(default="Nombre desconocido", max_length=255),
        ),
        migrations.AddField(
            model_name="instalaciondeportiva",
            name="servicios",
            field=models.TextField(default="Servicios no especificados"),
        ),
        migrations.AlterField(
            model_name="instalaciondeportiva",
            name="direccion",
            field=models.CharField(default="Dirección no disponible", max_length=300),
        ),
    ]
