# Generated by Django 5.1.1 on 2024-10-14 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("espacios", "0005_remove_instalaciondeportiva_delegacion_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="instalaciondeportiva",
            name="tipo",
        ),
    ]
