# Generated by Django 5.1.1 on 2024-10-14 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("espacios", "0006_remove_instalaciondeportiva_tipo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="instalaciondeportiva",
            name="nombre_instalacion",
        ),
        migrations.AddField(
            model_name="instalaciondeportiva",
            name="nombre",
            field=models.CharField(default="Sin nombre", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="instalaciondeportiva",
            name="alcaldia",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="instalaciondeportiva",
            name="direccion",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="instalaciondeportiva",
            name="horario",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="instalaciondeportiva",
            name="servicios",
            field=models.TextField(),
        ),
    ]
