# Generated by Django 5.1.1 on 2024-10-14 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("espacios", "0007_remove_instalaciondeportiva_nombre_instalacion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="instalaciondeportiva",
            name="deporte",
            field=models.CharField(default="Sin deporte", max_length=100),
        ),
    ]
