# Generated by Django 5.1.1 on 2024-10-14 06:09

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("espacios", "0008_instalaciondeportiva_deporte"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="instalaciondeportiva",
            name="deporte",
        ),
        migrations.CreateModel(
            name="Cancha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("etiqueta", models.CharField(max_length=100)),
                ("deporte", models.CharField(max_length=100)),
                ("medidas", models.CharField(max_length=100)),
                ("tipo_suelo", models.CharField(max_length=100)),
                ("senalamientos", models.TextField()),
                ("equipamiento", models.TextField()),
                (
                    "ubicacion",
                    django.contrib.gis.db.models.fields.PolygonField(srid=4326),
                ),
                (
                    "espacio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="espacios.instalaciondeportiva",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Partida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deporte", models.CharField(max_length=100)),
                ("fecha", models.DateField()),
                ("hora", models.TimeField()),
                (
                    "espacio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="espacios.instalaciondeportiva",
                    ),
                ),
                (
                    "jugadores_inscritos",
                    models.ManyToManyField(
                        related_name="partidas_inscritas", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "organizador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
