# Generated by Django 5.1.1 on 2024-10-14 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("espacios", "0009_remove_instalaciondeportiva_deporte_cancha_partida"),
    ]

    operations = [
        migrations.RenameField(
            model_name="espaciopublico",
            old_name="delegacion",
            new_name="alcaldia",
        ),
        migrations.RenameField(
            model_name="espaciopublico",
            old_name="tipo",
            new_name="horario",
        ),
        migrations.RemoveField(
            model_name="cancha",
            name="deporte",
        ),
        migrations.RemoveField(
            model_name="cancha",
            name="equipamiento",
        ),
        migrations.RemoveField(
            model_name="cancha",
            name="medidas",
        ),
        migrations.RemoveField(
            model_name="cancha",
            name="senalamientos",
        ),
        migrations.RemoveField(
            model_name="cancha",
            name="ubicacion",
        ),
        migrations.AddField(
            model_name="espaciopublico",
            name="costo",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="espaciopublico",
            name="servicios",
            field=models.TextField(default="No especificado"),
        ),
        migrations.AlterField(
            model_name="cancha",
            name="espacio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="canchas",
                to="espacios.espaciopublico",
            ),
        ),
        migrations.AlterField(
            model_name="espaciopublico",
            name="direccion",
            field=models.CharField(max_length=300),
        ),
    ]
