# Generated by Django 5.1.1 on 2024-10-14 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("espacios", "0010_rename_delegacion_espaciopublico_alcaldia_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cancha",
            name="tipo_suelo",
        ),
        migrations.AddField(
            model_name="cancha",
            name="deporte",
            field=models.CharField(default="no especificado", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="espaciopublico",
            name="acepta_mascotas",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="instalaciondeportiva",
            name="acepta_mascotas",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="instalaciondeportiva",
            name="deporte",
            field=models.CharField(default="no especificado", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cancha",
            name="espacio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="canchas",
                to="espacios.instalaciondeportiva",
            ),
        ),
        migrations.AlterField(
            model_name="espaciopublico",
            name="servicios",
            field=models.TextField(),
        ),
    ]
