# Generated by Django 5.1.1 on 2024-10-14 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("espacios", "0011_remove_cancha_tipo_suelo_cancha_deporte_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="instalaciondeportiva",
            name="gradas",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="instalaciondeportiva",
            name="gratuita",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="instalaciondeportiva",
            name="tipo_pasto",
            field=models.CharField(
                choices=[
                    ("Natural", "Natural"),
                    ("Sintético", "Sintético"),
                    ("Arcilla", "Arcilla"),
                    ("No especificado", "No especificado"),
                ],
                default="No especificado",
                max_length=50,
            ),
        ),
    ]
