# Generated by Django 5.1.1 on 2024-10-14 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("espacios", "0012_instalaciondeportiva_gradas_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instalaciondeportiva",
            name="servicios",
            field=models.TextField(blank=True, null=True),
        ),
    ]
