# Generated by Django 5.1.1 on 2024-09-17 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0004_alter_espaciopublico_delegacion'),
        ('foros', '0002_comentario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foro',
            old_name='contenido',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='foro',
            old_name='fecha',
            new_name='fecha_creacion',
        ),
        migrations.RenameField(
            model_name='foro',
            old_name='tema',
            new_name='titulo',
        ),
        migrations.RemoveField(
            model_name='foro',
            name='autor',
        ),
        migrations.AddField(
            model_name='foro',
            name='creador',
            field=models.CharField(default='sin clasificar', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comentario',
            name='usuario',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='foro',
            name='espacio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foros', to='espacios.espaciopublico'),
        ),
    ]
