# Generated by Django 5.1.1 on 2024-09-17 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0004_alter_espaciopublico_delegacion'),
        ('foros', '0003_rename_contenido_foro_descripcion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='fecha_comentario',
            new_name='fecha_creacion',
        ),
        migrations.AlterField(
            model_name='foro',
            name='espacio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foros', to='espacios.instalaciondeportiva'),
        ),
    ]
