# Generated by Django 5.1.1 on 2024-09-17 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foros', '0008_comentario_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='foro',
            name='creador',
            field=models.ForeignKey(default='sin clasificar', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='foro',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
